---
title: "Blog Post 4 "
author: ""
date: "2025-03-31"
date-modified: "2025-03-31"
draft: FALSE
---

  This week we explored our combined dataset more trying to understand different interactions that can be found in our data. The combined data set we had complied all different group types of students into a single column so to fix this we used pivot wider to expand the table with all of these different group types. However, an issue that arose with this dataset is the data isn't hanlded in such a way that would give values such as black females or homeless white males. Instead we can only see generilizations of the whole county which may make statistical modeling more challenging. Below is a table of 10 random rows in our dataset.

```{r}
suppressPackageStartupMessages(library(tidyverse))
combined_grad_data <- read_rds(here::here("dataset","combined_grad_income_expanded.rds"))

combined_grad_data|> sample_n(5) |>
  print(width = Inf)
```



  For statsitcal modeling with our dataset it seems that a linear model would be ideal as graduation rate is a continous function so it would not make sense to use a logistic model. To start next week we want to explore this more, testing out different response variables such as graduation rate or household income. Predictor varialbes we are intesreted in exploring are race, presence of diability, and gender. 